"""
Django settings for weblab project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import sys
from pathlib import Path
import dj_database_url
import subprocess

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

# ======================
# AUTOMATION SETUP
# ======================
def run_automations():
    """Run deployment automations when in production"""
    if 'render' in os.environ.get('RENDER', '').lower() or not DEBUG:
        # Auto-create SQLite database if it doesn't exist
        if not os.path.exists(BASE_DIR / 'db.sqlite3'):
            open(BASE_DIR / 'db.sqlite3', 'w').close()
        
        # Auto-run collectstatic
        subprocess.run(['python', 'manage.py', 'collectstatic', '--noinput'], check=False)
        
        # For PostgreSQL on Render (will auto-use if DATABASE_URL exists)
        if os.environ.get('DATABASE_URL'):
            subprocess.run(['python', 'manage.py', 'migrate', '--noinput'], check=False)

# ======================
# CORE SETTINGS
# ======================
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-auto-key-' + os.urandom(32).hex())
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'courses',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'weblab.urls'
WSGI_APPLICATION = 'weblab.wsgi.application'

# ======================
# DATABASE CONFIGURATION
# ======================
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR}/db.sqlite3',
        conn_max_age=600,
        engine='django.db.backends.sqlite3' if not os.environ.get('DATABASE_URL') else None
    )
}

# Auto-create tables for SQLite
if 'sqlite3' in DATABASES['default']['ENGINE'] and not os.path.exists(DATABASES['default']['NAME']):
    from django.db import connections
    for name in ['default']:
        connections[name].ensure_connection()

# ======================
# TEMPLATES
# ======================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ======================
# STATIC & MEDIA FILES
# ======================
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ======================
# OTHER CONFIGURATIONS
# ======================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Authentication
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_URL = '/login/'

# Email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@edulearn.com'

# ======================
# PRODUCTION SECURITY
# ======================
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ======================
# RUN AUTOMATIONS
# ======================
if 'runserver' not in sys.argv and 'test' not in sys.argv:
    run_automations()
